### PR TITLE
Mark as unmaintained

### PR DESCRIPTION
**Pull request by alexeagle**
In preparation for archiving the repo

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@ahumesky @ted-xie Any objections on archiving this repo?

**Comment by ahumesky** [comment]
The bazel team maintains this for miscellaneous items for the android rules.

**Comment by alexeagle** [comment]
@ahumesky that's good to hear. Since the most recent commit is 2y ago and no one has replied to any of the issues or pull requests here, it did not appear maintained.

**Comment by meteorcloudy** [comment]
@ahumesky Thanks for the confirmation!

**Pull request closed without merging**
